inputText = input().split()
a=float(inputText[0])
b=float(inputText[1])
c=float(inputText[2])

print("TRIANGULO: {:.3f}".format((a * c / 2)))
print("CIRCULO: {:.3f}".format((3.14159 * pow(c, 2))))
print("TRAPEZIO: {:.3f}".format(((a + b) / 2 * c)))
print("QUADRADO: {:.3f}".format((b * b)))
print("RETANGULO: {:.3f}".format((a * b)))